//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 GameMenu.rc 使用
//
#define IDD_DIALOG_TABDLG               1000
#define IDC_TAB1                        1000
#define IDD_DIALOG_SETTING              1002
#define IDC_STATIC_CFG                  1004
#define IDD_DIALOG_BASE                 1004
#define IDC_BUTTON_LoadCFG              1005
#define IDC_BUTTON_SavaCFG              1006
#define IDD_DIALOG_ESP                  1006
#define IDC_BUTTON_DefaultCFG           1007
#define IDC_STATIC_MENU                 1008
#define IDD_DIALOG_AIM                  1008
#define IDC_HOTKEY_MENU                 1009
#define IDC_STATIC_MenuHotKey           1010
#define IDD_DIALOG_KZ                   1010
#define IDC_CHECK_ShowMenuTip           1011
#define IDD_DIALOG_SCRIPT               1012
#define IDC_STATIC_FUN_ENALBE           1013
#define IDC_CHECK_BASEFUN               1014
#define IDD_DIALOG_LUA                  1014
#define IDC_CHECK_ESPFUN                1015
#define IDC_CHECK_RPN                   1015
#define IDC_CHECK_AIMFUN                1016
#define IDC_HOTKEY_RPN                  1016
#define IDD_DIALOG_SURVIVAL             1016
#define IDC_CHECK_WALLFUN               1017
#define IDC_CHECK_REROOM                1017
#define IDC_CHECK_KZFUN                 1018
#define IDC_HOTKEY_REROOM               1018
#define IDD_DIALOG_ZSHT                 1018
#define IDC_CHECK_SCRIPTFUN             1019
#define IDC_CHECK_RETROOM               1019
#define IDC_CHECK_MPFUN                 1020
#define IDC_HOTKEY_RETROOM              1020
#define IDD_DIALOG_MP                   1020
#define IDC_CHECK_NOFOG                 1021
#define IDC_CHECK_NIGHT                 1021
#define IDC_HOTKEY_NOFOG                1022
#define IDC_CHECK_ZSFUN                 1022
#define IDD_DIALOG_WEAPON               1022
#define IDC_CHECK_NOGAMEMENU            1023
#define IDC_STATIC_FUN_ENALBE2          1023
#define IDC_HOTKEY_NOGAMEMENU           1024
#define IDC_CHECK_KILLICO               1024
#define IDC_CHECK_CARDLAG               1025
#define IDC_CHECK_DEATHBOX              1025
#define IDC_HOTKEY_CARDLAG              1026
#define IDC_CHECK_SOCCER                1026
#define IDC_CHECK_ZBSBUY                1027
#define IDC_CHECK_GAME_FPS              1027
#define IDC_HOTKEY_ZBSBUG               1028
#define IDC_CHECK_ACTIVATE_WINDOW       1028
#define IDC_CHECK_THPER                 1029
#define IDC_CHECK_LIKE                  1029
#define IDC_HOTKEY_THPER                1030
#define IDC_LIST_SHOWHP                 1031
#define IDC_CHECK_EXITROOM              1032
#define IDC_HOTKEY_EXITROOM             1033
#define IDC_COMBO_KNIFE                 1034
#define IDC_COMBO3                      1035
#define IDC_COMBO_ZBSRPNOFFSET          1035
#define IDC_CHECK_ZBSBUY_DRONE          1036
#define IDC_HOTKEY_ZBSBUY_DRONE         1037
#define IDC_CHECK_NVG                   1038
#define IDC_CHECK_MPALIG                1039
#define IDC_CHECK_SHOWHP                1040
#define IDC_CHECK_KNIFE                 1041
#define IDC_HOTKEY_KNIFE                1042
#define IDC_CHECK_NOCHAT                1043
#define IDC_CHECK_SUPSEO                1044
#define IDC_CHECK_FRAMSEO               1045
#define IDC_CHECK_KICK                  1046
#define IDC_CHECK_ALTERTEAM             1047
#define IDC_COMBO_TEAM                  1048
#define IDC_CHECK_KNIFE3                1049
#define IDC_CHECK_PROGRESS_UNLOCK       1049
#define IDC_COMBO_RADAR_POS             1049
#define IDC_CHECK_NOLOTTER              1050
#define IDC_COMBO_PLAYERRADARTEAM       1050
#define IDC_CHECK_NOALLMSG              1051
#define IDC_COMBO_SOUDSRADAR            1051
#define IDC_CHECK_NVG7                  1052
#define IDC_CHECK_ANTI_ROOMKICK         1052
#define IDC_COMBO_WARING_POS            1052
#define IDC_CHECK_NVG8                  1053
#define IDC_CHECK_ZBSKICK               1053
#define IDC_COMBO_WARING_TEAM           1053
#define IDC_CHECK_NVG9                  1054
#define IDC_CHECK_FONT                  1054
#define IDC_COMBO_WALL_TYPE             1054
#define IDC_CHECK_KNIFE4                1055
#define IDC_CHECK_FLYING                1055
#define IDC_COMBO_WALL_TEAM             1055
#define IDC_HOTKEY_EXITROOM3            1056
#define IDC_HOTKEY_FLYING               1056
#define IDC_COMBO_OUTLINE_TEAM          1056
#define IDC_CHECK_KNIFE5                1057
#define IDC_CHECK_FLY2                  1057
#define IDC_COMBO_SIGHTBEAD_TYPE        1057
#define IDC_HOTKEY_EXITROOM4            1058
#define IDC_HOTKEY_FLYING2              1058
#define IDC_CHECK_NVG10                 1059
#define IDC_CHECK_ALTERRULE             1059
#define IDC_CHECK_NVG11                 1060
#define IDC_CHECK_ALTERSPRAY            1060
#define IDC_CHECK_NVG12                 1061
#define IDC_CHECK_ALTERWEAPON           1061
#define IDC_CHECK_NVG13                 1062
#define IDC_CHECK_QUEST                 1062
#define IDC_CHECK_NVG14                 1063
#define IDC_CHECK_ZSBRPN                1063
#define IDC_CHECK_NVG15                 1064
#define IDC_CHECK_DEFAulTCONSOLE        1064
#define IDC_CHECK_NVG16                 1065
#define IDC_CHECK_VXL_DESTROY           1065
#define IDC_CHECK_NVG17                 1066
#define IDC_CHECK_VXL_LIGHT             1066
#define IDC_EDIT1                       1067
#define IDC_EDIT_CHAR                   1067
#define IDC_EDIT_AIM_ANGLE              1067
#define IDC_EDIT_GAME_FPS               1067
#define IDC_CHECK_KNIFE6                1068
#define IDC_CHECK_CHAT                  1068
#define IDC_EDIT_AIM_PITCH              1068
#define IDC_CHECK_KNIFE7                1069
#define IDC_CHECK_BADWORD               1069
#define IDC_EDIT_AIM_YAW                1069
#define IDC_EDIT_COMMAND                1070
#define IDC_EDIT_AIM_SHOOT_ANGLE        1070
#define IDC_BUTTON_COMMAND              1071
#define IDC_CHECK_VXL_WEATHER           1072
#define IDC_CHECK_SHOWNAME              1072
#define IDC_CHECK_VXL_SKY               1073
#define IDC_CHECK_SHOWBOX               1073
#define IDC_HOTKEY_VXL_DESTROY          1074
#define IDC_CHECK_SHOWWEAPON            1074
#define IDC_CHECK_SHOWKM                1075
#define IDC_CHECK_SET_NET_STATUS        1075
#define IDC_CHECK_SHINE                 1076
#define IDC_CHECK_VXL_RESTART           1076
#define IDC_CHECK_SHOWTRACEMOVE         1077
#define IDC_HOTKEY_VXL_RESTART          1077
#define IDC_CHECK_TRACEANGLE            1078
#define IDC_CHECK_ALLKICK               1078
#define IDC_CHECK_SHOWITEM              1079
#define IDC_CHECK_OBSTP                 1079
#define IDC_CHECK_C4                    1080
#define IDC_CHECK_ALLKICK2              1080
#define IDC_CHECK_AUTO_KICK             1080
#define IDC_CHECK_CHECKSTATUS           1081
#define IDC_CHECK_PLAYERRADAR           1082
#define IDC_CHECK_SOUDSRADAR            1083
#define IDC_CHECK_WARING                1084
#define IDC_CHECK_SHOWDRONE             1085
#define IDC_CHECK_PARABOLA              1086
#define IDC_CHECK_PROPHUNT              1087
#define IDC_CHECK_SUPPLY                1088
#define IDC_CHECK_TRAP                  1089
#define IDC_COMBO_ESPTEAM               1090
#define IDC_CHECK_WALLHACK              1091
#define IDC_CHECK_AIM_KEY               1091
#define IDC_CHECK_OUTLINE               1092
#define IDC_COMBO_AIM_KEY               1092
#define IDC_CHECK_BLEEDING              1093
#define IDC_COMBO_AIM_TEAM              1093
#define IDC_CHECK_SIGHTBEAD             1094
#define IDC_COMBO_AIM_POS               1094
#define IDC_CHECK_GHOST                 1095
#define IDC_COMBO_AIM_TYPE              1095
#define IDC_CHECK_PLAYER_LIGHT          1096
#define IDC_COMBO_AIM_MODE              1096
#define IDC_CHECK_NOSMOKE               1097
#define IDC_CHECK_AIM_NORECOIL          1097
#define IDC_CHECK_NOFLASH               1098
#define IDC_CHECK_AIM_NORECOIL_VL       1098
#define IDC_COMBO_AIM_RECOILMODE        1099
#define IDC_CHECK_TRAP2                 1099
#define IDC_CHECK_ALL_ITEM              1099
#define IDC_CHECK_AIM_SHOWPLAYER        1100
#define IDC_CHECK_AIM_SHOW_SITION       1101
#define IDC_CHECK_AIM_SHOW_RECOIL       1102
#define IDC_CHECK_AIM_CAN_WEAPON        1103
#define IDC_COMBO_AIM_MOUSE_TYPE        1104
#define IDC_SLIDER1                     1105
#define IDC_COMBO_AIM_HIXBOX            1106
#define IDC_COMBO_AIM_HIXBOX_TYPE       1107
#define IDC_CHECK_AIM_ZBS_NOAIM         1108
#define IDC_CHECK_AIM_NO4               1109
#define IDC_CHECK_AIM_SHOOT             1110
#define IDC_CHECK_AIM_BARRIER           1111
#define IDC_STATIC_MOUSE                1112
#define IDC_BUTTON1                     1113
#define IDC_CHECK_KZ_278                1114
#define IDC_BUTTON2                     1114
#define IDC_CHECK_KZ_SPINHACK           1115
#define IDC_CHECK_KZ_JUMPBUG            1116
#define IDC_CHECK_KZ_INFO               1117
#define IDC_CHECK_KZ_HOP                1118
#define IDC_CHECK_KZ_AUTO_STRAFE        1119
#define IDC_COMBO_KZ_MCJ_KEY            1120
#define IDC_CHECK_MCJ                   1121
#define IDC_COMBO_COUNTER_MODE          1122
#define IDC_LIST2                       1123
#define IDC_COMBO_GAME_SPEED            1123
#define IDC_LIST_ZBS_AUTO_GANK          1124
#define IDC_CHECK_ZBS_GANK              1125
#define IDC_CHECK_ZBS_COUNTER           1126
#define IDC_CHECK_BUYHP                 1126
#define IDC_LIST_ZBS_AUTO_COUNTER       1127
#define IDC_HOTKEY_BUYHP                1127
#define IDC_CHECK_ZBS_S_AUTO_SKILL      1128
#define IDC_CHECK_ARMOR                 1128
#define IDC_HOTKEY_ARMOR                1129
#define IDC_CHECK_SPEED_ENABLE          1129
#define IDC_CHECK_ATK                   1130
#define IDC_COMBO_GAME_KEY              1130
#define IDC_HOTKEY_ATK                  1131
#define IDC_CHECK_SPEED_RECON           1131
#define IDC_COMBO_ZS_GRENADE            1132
#define IDC_CHECK_KZMODE                1132
#define IDC_CHECK_BULLET                1133
#define IDC_EDIT_SPEED_VALUE            1133
#define IDC_HOTKEY_BULLET               1134
#define IDC_EDIT_SPEED_RECONNECT_VALUE  1134
#define IDC_CHECK_BULLET2               1135
#define IDC_EDIT_ZSHT_X                 1135
#define IDC_COMBO_KZ_MODE               1135
#define IDC_HOTKEY_BULLET2              1136
#define IDC_EDIT_ZSHT_Y                 1136
#define IDC_CHECK_BUYGRENADE            1137
#define IDC_EDIT_ZSHT_Z                 1137
#define IDC_HOTKEY_ZS_GRENADE           1138
#define IDC_EDIT_ZSHT_COUNT             1138
#define IDC_CHECK_AUTO_BUY_BULLET       1139
#define IDC_COMBO_ZSHT_BUILD            1139
#define IDC_CHECK_AUTO_BUY_ARMOR        1140
#define IDC_CHECK_BUILD                 1140
#define IDC_CHECK_AUTO_BUY_ATK          1141
#define IDC_LIST1                       1141
#define IDC_CHECK_AUTO_DRUG30           1142
#define IDC_LIST3                       1142
#define IDC_CHECK_AUTO_DRUG100          1143
#define IDC_LIST4                       1143
#define IDC_CHECK_AFK                   1144
#define IDC_LIST5                       1144
#define IDC_CHECK_ROLE                  1145
#define IDC_LIST6                       1145
#define IDC_COMBO_ZS_ROLE               1146
#define IDC_LIST7                       1146
#define IDC_CHECK_AUTO_START_GAME       1147
#define IDC_CHECK_ZSHT_RESOURES         1147
#define IDC_CHECK_WEAPON                1147
#define IDC_CHECK_ZSHT_TAANSFER         1148
#define IDC_HOTKEY_MP_WEAPON            1148
#define IDC_CHECK_ZSHT_CONTRIBUTE       1149
#define IDC_CHECK_MP_MODE               1149
#define IDC_COMBO_MAP                   1150
#define IDC_BUTTON_CUTMAP               1151
#define IDC_CHECK_MP_GAMEMODE           1152
#define IDC_COMBO_GAMEMODE              1153
#define IDC_CHECK_MP_MAP                1154
#define IDC_CHECK_MP_GAINMUT            1155
#define IDC_CHECK_MP_HP                 1156
#define IDC_CHECK_MP_GOD                1157
#define IDC_CHECK_MP_SPEED              1158
#define IDC_CHECK_MP_AMMO               1159
#define IDC_CHECK_MP_AMMOSPEED          1160
#define IDC_CHECK_MP_RECOIL             1161
#define IDC_CHECK_MP_JUMP               1162
#define IDC_CHECK_MP_SOUL               1163
#define IDC_HOTKEY_SOUL                 1164
#define IDC_CHECK_MP_SOP                1165
#define IDC_CHECK_LUA_GOD               1165
#define IDC_HOTKEY_SOP                  1166
#define IDC_HOTKEY_GOD                  1166
#define IDC_CHECK_MP_RPN                1167
#define IDC_LIST_SOUND                  1167
#define IDC_CHECK_LUA_GOD_8133          1167
#define IDC_HOTKEY_GOD_8133             1168

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1024
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1168
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
